// Code generated by tools/openapi-ts from api/gen/http/openapi3.json. DO NOT EDIT.
// Regenerate with: make generate-api-types

export interface AddCandidatePayload {
  analyze?: boolean;
  binds?: string[];
  candidate_sql: string;
  id: string;
  verify_results?: boolean;
}

export interface AddCandidatePayload2 {
  analyze?: boolean;
  binds?: string[];
  candidate_sql: string;
  verify_results?: boolean;
}

export interface AggregateData {
  avg?: number;
  count?: number;
  max?: number;
  min?: number;
  std_dev?: number;
  sum?: number;
}

export interface AnomalyPointData {
  explanation?: string;
  period_label: string;
  reason: string;
  value: number;
}

export interface AskRequestBody {
  connection_id?: string;
  question: string;
}

export interface AskResult {
  question: string;
  report: Report;
  sql: string;
}

export interface ChartSuggestion {
  chart_type: string;
  label: string;
  reason: string;
}

export interface ChatRequestBody {
  connection_id?: string;
  question: string;
  session_id?: string;
}

export interface ChatResult {
  follow_ups: string[];
  history: ChatTurn[];
  question: string;
  report: Report;
  session_id: string;
  sql: string;
}

export interface ChatTurn {
  created_at: string;
  question: string;
  sql: string;
}

export interface CohortMetricData {
  cohort_label: string;
  periods?: CohortPeriodPointData[];
  retention_pct?: number;
}

export interface CohortPeriodPointData {
  period_label: string;
  value: number;
}

export interface ColumnInfo {
  name: string;
  type: string;
}

export interface ColumnQualityData {
  distinct_count: number;
  null_count: number;
  null_pct: number;
  total_rows: number;
}

export interface ComparePlansPayload {
  after_sql: string;
  analyze?: boolean;
  before_sql: string;
  binds?: string[];
  connection_id?: string;
  verify_results?: boolean;
}

export interface ComparePlansResult {
  after: ExplainQueryResult;
  before: ExplainQueryResult;
  diff: PlanComparisonDiff;
  metrics: PlanComparisonMetric[];
  result_after_row_count?: number;
  result_before_row_count?: number;
  result_checksum_equal?: boolean;
  result_equivalence_notes?: string;
  result_equivalence_status?: "VerifiedEqual" | "SampleMatch" | "Different" | "Unverified" | "NotRequested";
  result_sample_rows?: number;
}

export interface ConnectionInfo {
  id: string;
  name: string;
}

export interface ConnectionListResult {
  items: ConnectionInfo[];
}

export interface CorrelationPairData {
  column_a: string;
  column_b: string;
  pearson: number;
  spearman: number;
}

export interface CreateFromRegressionRequestBody {
  regression_alert_id: string;
}

export interface CreateInvestigationPayload {
  analyze?: boolean;
  calls?: number;
  connection_id?: string;
  mean_time_ms?: number;
  queryid?: string;
  rows?: number;
  sql: string;
  title: string;
  total_time_ms?: number;
}

export interface CreateRequestBody {
  name: string;
}

export interface CreateShareRequestBody {
  expires_in_hours?: number;
  report_id: string;
}

export interface Dashboard {
  created_at: string;
  id: string;
  name: string;
  updated_at: string;
  widgets: DashboardWidget[];
}

export interface DashboardListResult {
  items: Dashboard[];
}

export interface DashboardResolved {
  id: string;
  name: string;
  widgets: DashboardResolvedWidget[];
}

export interface DashboardResolvedWidget {
  id: string;
  position: number;
  refresh_seconds: number;
  report?: Report;
  saved_query?: SavedQuery;
  title?: string;
  widget_type: string;
}

export interface DashboardWidget {
  id: string;
  position: number;
  refresh_seconds: number;
  report_id?: string;
  saved_query_id?: string;
  title?: string;
  widget_type: string;
}

export interface DashboardWidgetInput {
  position?: number;
  refresh_seconds?: number;
  report_id?: string;
  saved_query_id?: string;
  title?: string;
  widget_type: string;
}

export interface DemoScenario {
  candidate_sql?: string;
  category: string;
  expected_improvement: string;
  id: string;
  problem: string;
  sql: string;
  title: string;
}

export interface DemoScenarioList {
  items: DemoScenario[];
}

export interface ExplainQueryPayload {
  analyze?: boolean;
  connection_id?: string;
  sql: string;
}

export interface ExplainQueryResult {
  diagnosis?: PlanDiagnosis;
  evidence_mode: "estimated" | "observed";
  findings: PlanFinding[];
  generic_plan?: boolean;
  plan: unknown;
  planning_time_ms?: number;
  request_wall_time_ms: number;
  server_execution_time_ms?: number;
  sql: string;
  total_cost: number;
}

export interface ExplainRequestBody {
  sql: string;
}

export interface ExplainResult {
  explanation: string;
  sql: string;
}

export interface GenerateReportPayload {
  connection_id?: string;
  saved_query_id?: string;
  sql: string;
}

export interface IndexAdvice {
  candidate_ddl?: string;
  issues?: string[];
  potential_benefit?: string;
  related_columns?: string[];
  related_indexes?: IndexDefinition[];
  storage_cost?: string;
  write_cost?: string;
}

export interface IndexDefinition {
  definition: string;
  include_columns?: string[];
  index_scans?: number;
  is_primary: boolean;
  is_unique: boolean;
  is_valid: boolean;
  key_columns?: string[];
  name: string;
  predicate?: string;
  size_bytes?: number;
  tuples_fetched?: number;
  tuples_read?: number;
}

export interface Investigation {
  candidate_explain?: ExplainQueryResult;
  candidate_sql?: string;
  candidates?: InvestigationCandidate[];
  comparison?: ComparePlansResult;
  connection_id: string;
  created_at: string;
  explain?: ExplainQueryResult;
  fix_applied_at?: string;
  fix_baseline_mean_ms?: number;
  fix_confirmed_mean_ms?: number;
  fix_measured_at?: string;
  fix_reference?: string;
  fix_status?: string;
  id: string;
  query_fingerprint?: string;
  report_id?: string;
  sql: string;
  stat_snapshot?: StatSnapshot;
  status: string;
  title: string;
  updated_at: string;
}

export interface InvestigationCandidate {
  binds?: string[];
  candidate_explain?: ExplainQueryResult;
  candidate_sql: string;
  comparison?: ComparePlansResult;
  cost_delta?: number;
  created_at: string;
  equivalence_status?: "VerifiedEqual" | "SampleMatch" | "Different" | "Unverified" | "NotRequested";
  id: string;
  is_current?: boolean;
  source?: string;
}

export interface InvestigationList {
  items: Investigation[];
  limit: number;
  offset: number;
}

export interface LLMError {
  code?: string;
  message: string;
  name: string;
}

export interface MetricsData {
  aggregates?: { [key: string]: AggregateData };
  cohorts?: CohortMetricData[];
  correlations?: CorrelationPairData[];
  data_quality?: { [key: string]: ColumnQualityData };
  investigation?: unknown;
  perf_suggestions?: string[];
  period_current_label?: string;
  period_previous_label?: string;
  time_series?: { [key: string]: TimeSeriesData };
  top_categories?: { [key: string]: TopCategoryData[] };
}

export interface NarrativeContent {
  drivers?: string[];
  headline: string;
  limitations?: string[];
  recommendations?: string[];
  takeaways: string[];
}

export interface NotFoundError {
  code?: string;
  message: string;
  name: string;
}

export interface PeriodComparisonItem {
  change?: number;
  change_percentage?: number;
  current: number;
  measure: string;
  previous?: number;
  trend: string;
}

export interface PeriodPointData {
  label: string;
  value: number;
}

export interface PlanComparisonDiff {
  added?: string[];
  improved?: string[];
  removed?: string[];
}

export interface PlanComparisonMetric {
  after: string;
  before: string;
  caveat?: string;
  change: string;
  evidence: string;
}

export interface PlanDiagnosis {
  causes?: PlanDiagnosisCause[];
  headline?: string;
  incidental?: PlanDiagnosisIncidental;
  raw_count: number;
  root_cause?: PlanDiagnosisCause;
  summary?: string;
}

export interface PlanDiagnosisCause {
  category: string;
  cost_share?: number;
  detail?: string;
  evidence?: string[];
  fix?: string;
  node_types?: string[];
  occurrences?: number;
  severity: string;
  title: string;
}

export interface PlanDiagnosisIncidental {
  categories?: string[];
  count: number;
  summary: string;
}

export interface PlanFinding {
  category?: string;
  confidence?: string;
  estimated_cost?: number;
  evidence?: string[];
  index_advice?: IndexAdvice;
  is_seq_scan: boolean;
  message: string;
  node_type: string;
  related_columns?: string[];
  relation?: string;
  schema?: string;
}

export interface QuerySuggestion {
  source: string;
  sql: string;
  title: string;
}

export interface RankCandidatesRequestBody {
  analyze?: boolean;
}

export interface RankedCandidate {
  category?: string;
  confidence?: string;
  cost_delta?: number;
  ddl?: string;
  execution_time_ms?: number;
  improved?: string[];
  kind: string;
  partitions_delta?: number;
  partitions_scanned?: number;
  projection_method?: string;
  rank?: number;
  rankable: boolean;
  rationale: string;
  sql?: string;
  total_cost?: number;
}

export interface RankedCandidateBaseline {
  execution_time_ms?: number;
  partitions_scanned?: number;
  total_cost?: number;
}

export interface RankedCandidateList {
  baseline?: RankedCandidateBaseline;
  candidates: RankedCandidate[];
  recommendation?: string;
}

export interface RegressionAlert {
  acknowledged: boolean;
  calls?: number;
  change_summary: string;
  change_type: string;
  connection_id: string;
  first_detected_at: string;
  id: string;
  impact: string;
  investigation_id?: string;
  last_seen_at?: string;
  mean_time_ms?: number;
  occurrences?: number;
  previous_alert_id?: string;
  query: string;
  queryid?: string;
  resolved_at?: string;
  rows?: number;
  source?: string;
  title: string;
  total_time_ms?: number;
}

export interface RegressionInbox {
  items: RegressionAlert[];
}

export interface Report {
  chart_suggestions?: ChartSuggestion[];
  connection_id: string;
  created_at: string;
  id: string;
  llm_model: string;
  llm_provider: string;
  metrics: MetricsData;
  narrative: NarrativeContent;
  saved_query_id?: string;
  sql: string;
}

export interface ReportList {
  items: Report[];
  limit: number;
  offset: number;
}

export interface ReportShareInfo {
  access_count: number;
  created_at: string;
  expires_at?: string;
  id: string;
  last_accessed_at?: string;
  revoked_at?: string;
}

export interface ReportShareLink {
  expires_at?: string;
  token: string;
  url: string;
}

export interface ReportShareList {
  items: ReportShareInfo[];
}

export interface ReportSimilarResult {
  items: SimilarReportItem[];
}

export interface RewriteCandidate {
  category?: string;
  confidence?: string;
  rationale: string;
  sql: string;
}

export interface RewriteRequestBody {
  instruction: string;
  report_id: string;
}

export interface RewriteSuggestionList {
  candidates: RewriteCandidate[];
}

export interface RunQueryPayload {
  connection_id?: string;
  limit?: number;
  sql: string;
}

export interface RunQueryResult {
  chart_suggestions?: ChartSuggestion[];
  columns: ColumnInfo[];
  execution_time_ms: number;
  limit: number;
  period_comparison?: PeriodComparisonItem[];
  period_current_label?: string;
  period_previous_label?: string;
  row_count: number;
  rows: unknown[][];
}

export interface SaveQueryPayload {
  connection_id?: string;
  description?: string;
  name: string;
  sql: string;
  tags?: string[];
}

export interface SavedQuery {
  connection_id: string;
  created_at: string;
  description?: string;
  id: string;
  name: string;
  sql: string;
  tags?: string[];
  updated_at: string;
}

export interface SavedQueryList {
  items: SavedQuery[];
  limit: number;
  offset: number;
}

export interface Schedule {
  connection_id: string;
  created_at: string;
  destination_target?: string;
  destination_type: string;
  enabled: boolean;
  id: string;
  interval_expr: string;
  last_error?: string;
  last_run_at?: string;
  last_status?: string;
  name: string;
  next_run_at?: string;
  saved_query_id?: string;
  sql?: string;
  timezone?: string;
  updated_at: string;
}

export interface ScheduleInput {
  connection_id?: string;
  destination_target?: string;
  destination_type: string;
  enabled?: boolean;
  interval_expr: string;
  name: string;
  saved_query_id?: string;
  sql?: string;
  timezone?: string;
}

export interface ScheduleListResult {
  items: Schedule[];
}

export interface ScheduleRunListResult {
  items: ScheduleRunRecord[];
}

export interface ScheduleRunRecord {
  attempt_count: number;
  completed_at?: string;
  failure_code?: string;
  failure_message?: string;
  id: string;
  report_id?: string;
  schedule_id: string;
  scheduled_for: string;
  started_at?: string;
  status: string;
}

export interface ScheduleRunResult {
  delivered: boolean;
  report_id?: string;
  schedule: Schedule;
}

export interface SchemaInfo {
  name: string;
  tables: TableInfo[];
}

export interface SchemaResult {
  schemas: SchemaInfo[];
}

export interface SecurityTrust {
  allowed_schemas: string[];
  analyze_policy: string;
  audit_mode: string;
  authentication: string;
  authorization_state: string[];
  connection_id: string;
  connection_mode: string;
  explain_analyze: string;
  external_llm_data: string;
  last_security_verification?: string;
  query_timeout_seconds: number;
  readonly: boolean;
  result_limit: number;
  tenant_isolation: string;
  tls: string;
}

export interface SimilarReportItem {
  connection_id: string;
  created_at: string;
  headline: string;
  id: string;
  similarity: number;
  sql: string;
}

export interface StatSnapshot {
  calls?: number;
  mean_time_ms?: number;
  queryid?: string;
  rows?: number;
  total_time_ms?: number;
}

export interface StatStatementRow {
  calls: number;
  mean_time_ms: number;
  query: string;
  queryid?: string;
  rows: number;
  total_time_ms: number;
}

export interface StatStatementsResult {
  items: StatStatementRow[];
  limit: number;
  order_by: string;
}

export interface SuggestedQueriesResult {
  suggestions: QuerySuggestion[];
}

export interface SuggestedQuestionsResult {
  questions: string[];
}

export interface TableInfo {
  columns: ColumnInfo[];
  name: string;
}

export interface TimeSeriesData {
  anomalies?: AnomalyPointData[];
  change?: number;
  change_percentage?: number;
  current_period: number;
  exponential_smooth_forecast?: number;
  forecast_ci_lower?: number;
  forecast_ci_upper?: number;
  holt_forecast?: number;
  moving_average?: number;
  next_period_forecast?: number;
  periods?: PeriodPointData[];
  predictive_summary?: string;
  previous_period?: number;
  seasonal_period?: number;
  seasonally_adjusted_forecast?: number;
  trend: string;
  trend_summary?: TrendSummaryData;
}

export interface TopCategoryData {
  category: string;
  percentage: number;
  value: number;
}

export interface TrendSummaryData {
  direction: string;
  explanation?: string;
  periods_used?: number;
  slope?: number;
  summary: string;
}

export interface UpdateFixPayload {
  fix_reference?: string;
  fix_status?: "proposed" | "verified" | "applied" | "confirmed" | "regressed" | "abandoned";
  id: string;
}

export interface UpdateFixPayload2 {
  fix_reference?: string;
  fix_status?: "proposed" | "verified" | "applied" | "confirmed" | "regressed" | "abandoned";
}

export interface UpdateRequestBody {
  name: string;
  widgets?: DashboardWidgetInput[];
}

export interface ValidationError {
  code?: string;
  message: string;
  name: string;
}

export interface WebhookDeliveryListResult {
  items: WebhookDeliveryRecord[];
}

export interface WebhookDeliveryRecord {
  attempt_count: number;
  completed_at?: string;
  created_at: string;
  destination_url: string;
  error_message?: string;
  http_status?: number;
  id: string;
  schedule_id?: string;
  status: string;
}

export interface WorkspaceOverview {
  database_time_hours: number;
  investigations_open: number;
  largest_regression_pct: number;
  queries_attention: number;
  queries_observed: number;
  reports_generated: number;
  sequential_scans_detected: number;
  temp_data_written_gb: number;
}

